### ISSUE TITLE
after click the bomb icon,  sd cannot be used and report this issue

### ISSUE THREAD

**Issue by jasoncow007** [Haoming02/sd-webui-memory-release#2]
Traceback (most recent call last):
      File "D:\sd-webui-aki-v4\modules\call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
      File "D:\sd-webui-aki-v4\modules\txt2img.py", line 55, in txt2img
        processed = processing.process_images(p)
      File "D:\sd-webui-aki-v4\modules\processing.py", line 725, in process_images
        sd_models.reload_model_weights()
      File "D:\sd-webui-aki-v4\modules\sd_models.py", line 732, in reload_model_weights
        sd_model = reuse_model_from_already_loaded(sd_model, checkpoint_info, timer)
      File "D:\sd-webui-aki-v4\modules\sd_models.py", line 681, in reuse_model_from_already_loaded
        send_model_to_cpu(sd_model)
      File "D:\sd-webui-aki-v4\modules\sd_models.py", line 541, in send_model_to_cpu
        if m.lowvram:
    AttributeError: 'NoneType' object has no attribute 'lowvram'

**Comment by Haoming02** [comment]
Well, I can't fix that. I merely call the functions provided by the Webui.
That error is not on my part.
